### ISSUE TITLE
About the cytosine_ref.rds in 01-bed-to-granges.r

### ISSUE THREAD

**Issue by Jiangstte** [cancer-genomics/reproduce_lucas_wflow#1]
Don't know the cytosine_ref.rds in 01-bed-to-granges.r, Could you consult about the relevant format or provide the file？ thank you.

**Comment by ACSoupir** [comment]
Has there been any update to the `cytosine_ref.rds` file?

**Comment by almanza-d** [comment]
Bumping this, where do I find such file?

**Comment by rscharpf** [comment]
Hi all,  The `cytosine_ref.rds` file was generated as follows:
```
library(GenomicRanges)
library(Biostrings)
library(BSgenome.Hsapiens.UCSC.hg19)
library(Homo.sapiens)
cytosines <- vmatchPattern("C", Hsapiens)
```
We did not include this file in the repository because of its size.  Thanks.

**Comment by EarnestJJ** [comment]
> Has there been any update to the `cytosine_ref.rds` file?

Hi, Dr. Soupir
    I wonder if you can reproduce this article successfully. if  so,  do you know how the file bins_**5mb.csv** at _line 21_ in  path **_reproduce_lucas_wflow-master/code/preprocessing/bin_corrected.sh_** was obtained ? Because this file will be used in the R script later, there is no instruction on how to get it in any of the previous operations. Thank you!

**Comment by yiping801026** [comment]
> Hi, Dr. Soupir I wonder if you can reproduce this article successfully. if so, do you know how the file bins_**5mb.csv** at _line 21_ in path **_reproduce_lucas_wflow-master/code/preprocessing/bin_corrected.sh_** was obtained ? Because this file will be used in the R script later, there is no instruction on how to get it in any of the previous operations. Thank you!

Hi, Earnest,
I met the same problem, that cannot find the 'bins_5mb.csv' for further use. Did you figure out how to treat it? Thanks in advance!
Yi
