### ISSUE TITLE
A serious issue urgently needs to be clarified

### ISSUE THREAD

**Issue by liujilei2233** [cancer-genomics/reproduce_lucas_wflow#3]
Dear author, 
The following code is confused when I am working with my own data using your ```code/preprocessing/04-getZscores.r``` . I wonder how ```ref54_bins ```is generated. 
Thanks a lot.

https://github.com/cancer-genomics/reproduce_lucas_wflow/blob/394576177f78961816e7adc486d275897be39015/code/preprocessing/04-getZscores.r#L39

**Comment by liukeweiaway** [comment]
I have the same issue. Have you solved it?

**Comment by liukeweiaway** [comment]
> Dear author, The following code is confused when I am working with my own data using your `code/preprocessing/04-getZscores.r` . I wonder how `ref54_bins `is generated. Thanks a lot.
> 
> https://github.com/cancer-genomics/reproduce_lucas_wflow/blob/394576177f78961816e7adc486d275897be39015/code/preprocessing/04-getZscores.r#L39
I have the same issue. Have you solved it?
